"""
Pure app.c transformations for TB-03F firmware builds (no file I/O, no build).

Applied to the pristine upstream app.c for every variant, so builds never depend on the state a
previous build left behind.
"""

import hashlib
import re

TIMER_TICK_MIN = 2              # blt_soft_timer_add(..., 2 min) in app.c
BLE_ADV_UNIT_MS = 0.625         # BLE advertising interval unit
KEY_LEN = 28                    # P-224 X coordinate
NUM_KEYS = 3
SLOT_LEN = KEY_LEN * NUM_KEYS   # 84 bytes
MARKER_TAG = b"TB03F-KEYSLOT-v1"
KNOWN_POWERS = ("RF_POWER_P10p29dBm", "RF_POWER_P0p04dBm")

KEYS_RE = re.compile(r"static\s+u8\s+public_keys\s*\[3\]\s*\[28\]\s*=\s*\{.*?\n\s*\};", re.S)
BLOCK_RE = re.compile(r"/\* BUILD_CONFIG_BEGIN.*?BUILD_CONFIG_END \*/\n\n?", re.S)


def keyslot_marker() -> bytes:
    """84-byte placeholder for public_keys: non-zero (keeps the array in .data, i.e. in the
    flash image) and high-entropy (occurs exactly once in the binary)."""
    out = bytearray(MARKER_TAG)
    i = 0
    while len(out) < SLOT_LEN:
        out += hashlib.sha256(MARKER_TAG + bytes([i])).digest()
        i += 1
    return bytes(out[:SLOT_LEN])


def adv_units(ms: int) -> int:
    return round(ms / BLE_ADV_UNIT_MS)


def validate_config(cfg: dict) -> dict:
    if not 20 <= cfg["adv_interval_ms"] <= 10240:
        raise ValueError("adv interval must be 20..10240 ms")
    if not re.fullmatch(r"RF_POWER_[A-Za-z0-9_]+", cfg["power"]):
        raise ValueError("power must be an RF_POWER_* macro name")
    if not 1 <= cfg["battery_days"] <= 90:
        raise ValueError("battery days must be 1..90 (16-bit tick counter)")
    if cfg["rotation_min"] < TIMER_TICK_MIN or cfg["rotation_min"] % TIMER_TICK_MIN:
        raise ValueError(f"rotation minutes must be a multiple of {TIMER_TICK_MIN}")
    return cfg


def normalize_newlines(text: str) -> str:
    return text.replace("\r\n", "\n")


def apply_keys(text: str, slot: bytes) -> str:
    """Replace the public_keys initializer with the 84 bytes in `slot` (3 x 28)."""
    if len(slot) != SLOT_LEN:
        raise ValueError(f"key slot must be {SLOT_LEN} bytes, got {len(slot)}")
    rows = [
        f"  {{ /* Key {i + 1} */ " + ", ".join(f"0x{b:02x}" for b in slot[i * KEY_LEN:(i + 1) * KEY_LEN]) + " }"
        for i in range(NUM_KEYS)
    ]
    new_array = "static u8 public_keys[3][28] = {\n" + ",\n".join(rows) + "\n};"
    new_text, n = KEYS_RE.subn(lambda m: new_array, normalize_newlines(text), count=1)
    if n != 1:
        raise RuntimeError("public_keys array not found in app.c")
    return new_text


def config_block(cfg: dict) -> str:
    return (
        "/* BUILD_CONFIG_BEGIN (generated by scripts/fwpatch.py) */\n"
        f"#define MY_RF_POWER_INDEX     {cfg['power']}\n"
        f"#define MY_ADV_INTERVAL       {adv_units(cfg['adv_interval_ms'])} /* {cfg['adv_interval_ms']} ms */\n"
        f"#define SEND_BATTERY_CHARGE   {1 if cfg['send_battery'] else 0}\n"
        f"#define BATTERY_UPDATE_DAYS   {cfg['battery_days']}\n"
        f"#define BATTERY_UPDATE_TICKS  (BATTERY_UPDATE_DAYS * 24 * 60 / {TIMER_TICK_MIN}) "
        f"/* soft timer ticks every {TIMER_TICK_MIN} min */\n"
        f"#define KEY_ROTATION_MINUTES  {cfg['rotation_min']}\n"
        f"#define KEY_ROTATION_TICKS    (KEY_ROTATION_MINUTES / {TIMER_TICK_MIN}) "
        f"/* soft timer ticks every {TIMER_TICK_MIN} min */\n"
        "/* BUILD_CONFIG_END */\n"
    )


def apply_config(text: str, cfg: dict) -> str:
    """Insert the BUILD_CONFIG block and route app.c through it; idempotent."""
    validate_config(cfg)
    text = normalize_newlines(text)

    text = BLOCK_RE.sub("", text)
    text = re.sub(r"^[ \t]*(//)?[ \t]*#define[ \t]+MY_RF_POWER_INDEX.*\n", "", text, flags=re.M)
    anchor = "#define STATUS_FLAG_BATTERY_MASK"
    if anchor not in text:
        raise RuntimeError("Anchor for config block not found in app.c")
    text = text.replace(anchor, config_block(cfg) + "\n" + anchor, 1)

    text = re.sub(r"\bADV_INTERVAL_2S\b", "MY_ADV_INTERVAL", text)
    if "MY_ADV_INTERVAL," not in text:
        raise RuntimeError("bls_ll_setAdvParam interval not routed through MY_ADV_INTERVAL")

    text, n = re.subn(r"\+\+ble_update_counter\s*<\s*[A-Za-z_0-9]+",
                      "++ble_update_counter < KEY_ROTATION_TICKS", text)
    if n != 1:
        raise RuntimeError("ble_update_counter comparison not found in app.c")

    text, n = re.subn(r"\+\+battery_update_counter\s*<\s*[A-Za-z_0-9]+",
                      "++battery_update_counter < BATTERY_UPDATE_TICKS", text)
    if n != 1:
        raise RuntimeError("battery_update_counter comparison not found in app.c")

    if "#if !SEND_BATTERY_CHARGE" not in text:
        text, n = re.subn(
            r"(int\s+update_battery_status\s*\(void\)\s*\{\n)",
            r"\1#if !SEND_BATTERY_CHARGE\n  return 0; /* battery status disabled: no ADC read, flags stay 0 */\n#endif\n",
            text, count=1)
        if n != 1:
            raise RuntimeError("update_battery_status() not found in app.c")

    if "PATCH: ADC power off" not in text:
        text, n = re.subn(
            r"(batt_vol_mv\s*=\s*\(adc_result\s*\*\s*1200\s*\*\s*8\)\s*/\s*0x2000;\n)",
            r"\1\n  /* PATCH: ADC power off - don't leave the SAR ADC running between readings */\n"
            r"  adc_power_on_sar_adc(0);\n"
            r"  adc_hw_initialized = 0; /* next reading re-runs the full init */\n",
            text, count=1)
        if n != 1:
            raise RuntimeError("batt_vol_mv calculation not found in read_battery_voltage()")

    if "PATCH: TX power after re-init" not in text:
        anchor = "  bls_ll_setAdvEnable(1); // Restart advertising"
        if text.count(anchor) != 1:
            raise RuntimeError("'Restart advertising' line not found (or not unique) in reinit_ble_with_key()")
        text = text.replace(
            anchor,
            "  /* PATCH: TX power after re-init - the init calls above may reset it */\n"
            "  rf_set_power_level_index(MY_RF_POWER_INDEX);\n" + anchor, 1)

    return text


def power_token(power: str) -> str:
    """RF_POWER_P10p29dBm -> p10p29, RF_POWER_N3p23dBm -> n3p23."""
    m = re.fullmatch(r"RF_POWER_([PN]\d+p\d+)dBm", power)
    return m.group(1).lower() if m else power.removeprefix("RF_POWER_").lower()


def variant_id(cfg: dict) -> str:
    bat = f"bat{cfg['battery_days']}d" if cfg["send_battery"] else "batoff"
    return f"adv{cfg['adv_interval_ms']}_{power_token(cfg['power'])}_{bat}_rot{cfg['rotation_min']}"
