#!/usr/bin/env python3
"""
Write P-224 test vectors for the browser key generator (web/js/p224.js), computed with the
`cryptography` package as an independent reference. Throwaway keys: never flash these.

  python scripts/gen_p224_vectors.py > test/fixtures/p224_vectors.json
"""

import base64
import hashlib
import json
import secrets

from cryptography.hazmat.primitives.asymmetric import ec

N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFF16A2E0B8F03E13DD29455C5C2A3D


def vector(d: int) -> dict:
    x = ec.derive_private_key(d, ec.SECP224R1()).public_key().public_numbers().x
    priv, adv = d.to_bytes(28, "big"), x.to_bytes(28, "big")
    return {
        "privateKey": base64.b64encode(priv).decode(),
        "advertisementKey": base64.b64encode(adv).decode(),
        "hashedAdvKey": base64.b64encode(hashlib.sha256(adv).digest()).decode(),
    }


def main():
    scalars = [1, 2, 3, N - 1, N - 2, 2**223 + 12345, 0x1234567890ABCDEF]
    scalars += [secrets.randbelow(N - 1) + 1 for _ in range(10)]
    print(json.dumps({
        "_note": "TEST VECTORS ONLY - generated by scripts/gen_p224_vectors.py with `cryptography`. Never use on a device.",
        "vectors": [vector(d) for d in scalars],
    }, indent=2))


if __name__ == "__main__":
    main()
